updates with respect to nodejs buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,66 +1,92 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-# fail fast
-set -e
+set -e            # fail fast
+set -o pipefail   # don't ignore exit codes when piping output
+# set -x          # enable debugging
+
+# Configure directories
+build_dir=$1
+cache_dir=$2
+env_dir=$3
+
+bp_dir=$(cd $(dirname $0); cd ..; pwd)
 
 # clean up leaking environment
 unset GIT_DIR
 
-# parse args
-BUILD_DIR=$1
-CACHE_DIR=$2
+# Load some convenience functions like status(), echo(), and indent()
+source $bp_dir/bin/common.sh
 
-function indent() {
-  c='s/^/       /'
-  case $(uname) in
-    Darwin) sed -l "$c";;
-    *)      sed -u "$c";;
-  esac
-}
+source "$build_dir/_git.cfg"
 
-source "$BUILD_DIR/_git.cfg"
-
-if [[ ! $GIT_VERSION ]]; then
-  GIT_VERSION=1.9.1
+# Recommend using semver ranges in a safe manner
+if [ ! $git_version ]; then
+  protip "You can specify a git version in _git.cfg"
+  git_version=""
+elif [ "$git_version" == "*" ]; then
+  protip "Avoid using ranges like '*' in _git.cfg"
+  git_version=""
+elif [ ${git_version:0:1} == ">" ]; then
+  protip "Avoid using ranges starting with '>' in _git.cfg"
+  git_version=""
 fi
 
-BIN_DIR=$BUILD_DIR/vendor/git
-
-mkdir -p "$BIN_DIR"
-
-if [[ -d "$CACHE_DIR/vendor/git-$GIT_VERSION" ]]; then
-  echo -n "-----> Using cached Git $GIT_VERSION..."
-  cp -R "$CACHE_DIR/vendor/git-$GIT_VERSION/" "$BIN_DIR"
-  echo "       done."
+# Output info about requested version and resolved git version
+if [ "$git_version" == "" ]; then
+  git_version="master"
+  git_url="https://github.com/git/git/archive/master.tar.gz"
+  git_src_dir="git-master"
+  status "Defaulting to latest master branch"
 else
-  echo -n "-----> Cleaning cached Git versions..."
-  rm -rf "$CACHE_DIR/vendor/git-*"
-  echo "       done."
-
-  echo -n "-----> Downloading Git $GIT_VERSION..."
-  cd "$BUILD_DIR"
-  curl --silent --location "https://github.com/git/git/archive/v$GIT_VERSION.tar.gz" | tar xz
-  cd "git-$GIT_VERSION"
-  echo "       done."
-
-  echo -n "-----> Compiling Git..."
-  make NO_TCLTK=YesPlease NO_PERL=YesPlease NO_GETTEXT=YesPlease NO_SVN_TESTS=YesPlease NO_MSGFMT=YesPlease NO_MSGFMT_EXTENDED_OPTIONS=YesPlease CFLAGS="-Os -g0 -Wall" prefix="$BIN_DIR" install clean | indent
-  echo "       done."
-  echo "-----> Git was Installed at: $BIN_DIR"
-
-  echo -n "-----> Cleaning up Git source files..."
-  cd ..
-  rm -rf "git-$GIT_VERSION"
-  echo "       done."
-
-  echo -n "-----> Caching Git binaries..."
-  mkdir -p "$CACHE_DIR/vendor"
-  cp -R "$BIN_DIR/" "$CACHE_DIR/vendor/git-$GIT_VERSION"
-  echo "       done."
+  git_url="https://github.com/git/git/archive/v$git_version.tar.gz"
+  git_src_dir="git-$git_version"
+  status "Requested git version:  $git_version"
 fi
 
-echo -n "-----> Building runtime environment"
-mkdir -p $BUILD_DIR/.profile.d
-echo "export PATH=\"\$HOME/vendor/git/bin:\$PATH\";" > $BUILD_DIR/.profile.d/git.sh
-echo "       done."
+bin_dir=$build_dir/vendor/git
+
+mkdir -p "$bin_dir"
+
+if [ "$git_version" == "master" ] || ! test -d $cache_dir/git || ! test -f $cache_dir/git/.heroku/git-version || [ $(cat $cache_dir/git/.heroku/git-version) != "$git_version" ]; then
+  status "Git version changed since last build; rebuilding dependencies"
+
+  # Persist goodies like git-version in the slug
+  mkdir -p $build_dir/.heroku
+
+  # Save resolved git version in the slug for later reference
+  echo $git_version > $build_dir/.heroku/git-version
+
+  # Purge git-related cached content, being careful not to purge the top-level
+  # cache, for the sake of heroku-buildpack-multi apps.
+  status "Cleaning cached Git version..."
+  rm -rf $cache_dir/git
+  mkdir -p $cache_dir/git
+
+  status "Downloading Git $git_version..."
+  curl $git_url -s -l -o - | tar xzf - -C $build_dir
+  cd "$build_dir"
+  cd $git_src_dir
+
+  status "Compiling Git..."
+  make NO_TCLTK=YesPlease NO_PERL=YesPlease NO_GETTEXT=YesPlease NO_SVN_TESTS=YesPlease NO_MSGFMT=YesPlease NO_MSGFMT_EXTENDED_OPTIONS=YesPlease CFLAGS="-Os -g0 -Wall" prefix="$bin_dir" install clean | indent
+  status "Git was Installed at: $bin_dir"
+
+  status "Cleaning up Git source files..."
+  cd ..
+  rm -rf $git_src_dir
+
+  status "Caching Git binaries..."
+  cp -R "$bin_dir/" "$cache_dir/git"
+  # Copy goodies to the cache
+  cp -r $build_dir/.heroku $cache_dir/git
+
+else
+  status "Using cached Git $git_version..."
+  cp -R "$cache_dir/git/" "$bin_dir"
+fi
+
+# Update the PATH
+status "Building runtime environment"
+mkdir -p $build_dir/.profile.d
+echo "export PATH=\"\$HOME/vendor/git/bin:\$PATH\";" > $build_dir/.profile.d/git.sh
